const scheduler = require('./src/cron-scrape')
const dataManager = require('./src/dataManager')
const express = require('express')
const app = express()
app.set('view engine', 'pug')
app.set('views', './src/views')
app.get('/', (req,res) => {
  const mediaItems = dataManager.getMediaItems()
  res.render('index', { mediaItems })
})
app.listen(3000, () => console.log("Listening on port 3000"))